### ISSUE TITLE
GNB gnashing fang issue

### ISSUE THREAD

**Issue by YannisPapa** [PunishXIV/WrathCombo#103]
When the gnashing fang collection is turned on with only continuation added then you try to turn on no mercy collection it disables gnashing fang. it doesn't seem like adding bow shock to no mercy and continuation to gnashing fang should conflict. But great work with the addon, love what you are doing keep it up!

**Comment by fmieres** [comment]
The same happens with me, without no mercy enabled. 
Gnashing fang features + continuation enabled:
* gnashing fang turns to savage claw
* keen edge is replaced by continuation during gnasing fang combo
