### ISSUE TITLE
[Feature Request] [PVP] [BRD] Adding target hp slider to Harmonic Arrow

### ISSUE THREAD

**Issue by PikachusDimples** [PunishXIV/WrathCombo#120]
I like to use Harmonic Arrow as a final stab as a target is say around 15-20% hp, often leads to a knockout.

As Harmonic Arrow tends to interfere with the rotation if not all 4 charges are used, is it possible to add a parameter to the HA option of a "Target HP slider"? 

Saving all 4 charges for the hp% specified. 

Thanks for your consideration, and the work you do in general.

**Comment by edewen** [comment]
There is an execute mode in the current pr that will fire off harmonic when a target drops below 12k at any charge. 2 or more charges will be an instant kill. 1 will be close. 

https://github.com/PunishXIV/WrathCombo/pull/107

**Comment by zbee** [comment]
This was instead added in #143.
