### ISSUE TITLE
[MCH] So, the 92+ AoE rotation...

### ISSUE THREAD

**Issue by neongrey** [PunishXIV/WrathCombo#126]
Autocrossbow might just be the worst skill in the game. Once your oGCDs upgrade into Double Check and Checkmate, Autocrossbow now only becomes a gain at 6+ targets. Prior to auto-mode this was out of scope really, but I'd like to raise this again. If nothing else I wouldn't mind a toggle in aoe advanced mode to just never use autocrossbow and substitute blazing shot from level 92 up, since that's applicable to both auto and manual use. 

This also raises the notion in my mind that the AoE threshold setting in the auto mode settings should probably be set per job. For once, this isn't MCH special-casing (though they would benefit, given scattergun), it's that I'm pretty sure tanks want to AoE right from 2 targets, while most other jobs gain on 3. This might be better broken out into a separate issue though?

**Comment by Kagekazu** [comment]
> Autocrossbow might just be the worst skill in the game. Once your oGCDs upgrade into Double Check and Checkmate, Autocrossbow now only becomes a gain at 6+ targets. Prior to auto-mode this was out of scope really, but I'd like to raise this again. If nothing else I wouldn't mind a toggle in aoe advanced mode to just never use autocrossbow and substitute blazing shot from level 92 up, since that's applicable to both auto and manual use.

Sure, I can make an option for advanced to swap to blazing shot at lvl 92+


> This also raises the notion in my mind that the AoE threshold setting in the auto mode settings should probably be set per job. For once, this isn't MCH special-casing (though they would benefit, given scattergun), it's that I'm pretty sure tanks want to AoE right from 2 targets, while most other jobs gain on 3. This might be better broken out into a separate issue though?

This might best be put in a seperate issue, since its a bit bigger than just MCH.
