### ISSUE TITLE
Auto-target AoE threshold should probably be set by job

### ISSUE THREAD

**Issue by neongrey** [PunishXIV/WrathCombo#127]
Different jobs begin to gain on AoE at different enemy counts-- I'm pretty sure that all tanks' main aoe gcds and machinist's scattergun (if you're prioritizing heat, which of course you are) are a gain on 2 targets, whereas non-dumb dps gain on 3. For ideal set-it-and-forget-it, you probably want to configure the threshold on a per-job basis.

**Comment by zbee** [comment]
According to The Balance: All tanks are 3+ targets, and MCH is [still primarily 3+ targets](https://www.thebalanceffxiv.com/jobs/ranged/machinist/basic-guide/#multi-target-rotation-and-optimization); plus all other jobs that I'm aware of.
Regarding MCH, it's only filler and 2 niche cases where it can be <3, so even MCH I wouldn't recommend setting to 2 - plus the extra logic that it seems would be needed in the AoE combo to hit these sweet spots, from a cursory glance.
I don't think that the scenarios (<3 adds left in a pack) where this *could* apply warrant this overhaul.
