### ISSUE TITLE
Samurai broken when picking the '_______ Combo' features (ex. Kasha Combo, Gekko Combo ect)

### ISSUE THREAD

**Issue by neotantrix** [PunishXIV/WrathCombo#130]
When choosing to have the last attack in a combo replaced with its chain eg, Yukikaze, Kasha, Gekko, Oka, and Mangetsu, they no longer work. This happened to me ONLY after reaching level 92 and unlocking the gyofu  new first step in the combos but is not working even if synced down below that level once reaching level 92. I suspect gyofu is interfering somehow and gyofucking our day up.

**Comment by zbee** [comment]
Already fixed in #112.

**Comment by neotantrix** [comment]
ah then its not pushed i guess? its still broken for me

**Comment by zbee** [comment]
Correct, that PR is not merged yet, and after that it waits for a release to be made.
