### ISSUE TITLE
[Feature Request] Ability to turn on autorotation but not the combo hotbar replacing part

### ISSUE THREAD

**Issue by PhilShwartz** [PunishXIV/WrathCombo#134]
Would be nice to be able to use autorotation but NOT the combo part
just want something to automate boring content using autoduty while still being able to do my rotation myself.

**Comment by zbee** [comment]
Profiles, Simple Modes having a Auto-Only state, or Simple Mode for your job being the default Auto-Mode if you did not turn on auto on Advanced are all some options that I like that would solve this.

**Comment by zbee** [comment]
Fixed in e3a1519 with the addition of a new feature. Will be in 1.0.0.4.

**Comment by zbee** [comment]
1.0.0.4 is now live, this is now implemented.
Turn off the combo part with `/wrath combo off`.
