### ISSUE TITLE
Standalone combos not working

### ISSUE THREAD

**Issue by Vodka1235** [PunishXIV/WrathCombo#135]
Since patch day individual combo chains have not been working. The examples I've come across are Gnashing Fang being relegated to its own button and the entirety of SAM. Combos refuse to start with Hakaze/Gyofu but then continue correctly if that skill is manually inputted from a seperate button. This does not affect the Auto-Mode.

**Comment by Kagekazu** [comment]
duplicate of #130 

fixed in #112

**Comment by Vodka1235** [comment]
ah my mistake, thanks chief
