### ISSUE TITLE
[Bug] Job Opener level 100

### ISSUE THREAD

**Issue by BungzeroQ** [PunishXIV/WrathCombo#138]
I just pulled the latest git update. It seems like the Opener system has issues with every job—it’s not progressing to the next step.

**Comment by Kagekazu** [comment]
i just tried MCH, SAM, DRG and MNK opener and got no issues

**Comment by Kagekazu** [comment]
> I just pulled the latest git update. It seems like the Opener system has issues with every job—it’s not progressing to the next step.

Got some more info about what happens? 
Anything in /xllog?
any specific job?

Have u tried restarting ur game?

**Comment by BungzeroQ** [comment]
https://github.com/user-attachments/assets/0098921a-6d55-4926-b12f-e1106ef0a151

![image](https://github.com/user-attachments/assets/a0b50ecc-5882-43ae-8bcb-cc7fc7812a32)

But if I use something release plugin, it works fine. Did something happen to the latest branch? Because it worked fine yesterday.

**Comment by Kagekazu** [comment]
> Recording.2024-11-27.221208.mp4 
> ![image](https://private-user-images.githubusercontent.com/139851815/390465700-a0b50ecc-5882-43ae-8bcb-cc7fc7812a32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MjA5MjEsIm5iZiI6MTczMjcyMDYyMSwicGF0aCI6Ii8xMzk4NTE4MTUvMzkwNDY1NzAwLWEwYjUwZWNjLTU4ODItNDNhZS04YmNiLWNjN2ZjNzgxMmEzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QxNTE3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWU5YWExMDY0ZTUxY2Q4Mjg4NjliYTlkMzk4ZjdlODliMTQxZTU0NTE3ZDA4NzI4ODBmYzc4N2Y1YWFiMjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3cf6TtHRZmdXAJZO7EAey8lpihBK8gLmPjCxwKhFg68)
> 
> But if I use something release plugin, it works fine. Did something happen to the latest branch? Because it worked fine yesterday.

Is it only viper? Or other jobs aswell? Since u said all the openers have issues

**Comment by BungzeroQ** [comment]
Uploading Recording 2024-11-27 222355.mp4…

MCH

**Comment by Kagekazu** [comment]
> Uploading Recording 2024-11-27 222355.mp4…
> 
> MCH

That is not on live, correct?
Since i am in the middle of PR #140 , and i got no issue with the opener

**Comment by Kagekazu** [comment]
Fixed with latest commit on main
