### ISSUE TITLE
[BUG] WrathCombo Max Melee

### ISSUE THREAD

**Issue by KSVKovrov** [PunishXIV/WrathCombo#142]
Currently WrathCombo does not account for weaponskill range as being in melee range turning on ranged features outside of the autoattack range while still within the weaponskill range.

**Comment by Kagekazu** [comment]
Can u give an example of which skill it should be able to do eventough it cant auto attack?

It should account for the range on the tooltip

**Comment by KSVKovrov** [comment]
It applies to pretty much every ability that can still be used in weaponskill range like the normal GCD, turning off the ranged uptime options allows them to be used without problem as expected but turning them on will do the effect of using them before leaving range completely.
First noted this behavior on savage after swapping to wrath and can replicate it consistently across instances and targets too.
I.E: NIN throwing dagger option/gapclosing options or lightning shot on GNB will be used when their options are turned on and still within weaponskill range 
GNB example
![image](https://github.com/user-attachments/assets/3ecffb0a-b46c-41fa-a579-a45d20098013)
![image](https://github.com/user-attachments/assets/65125e3f-eb73-46a7-afa0-262aa47b95b0)
SAM example
![image](https://github.com/user-attachments/assets/5d2e2f22-5b4c-48ad-81ed-07f6821b299d)
![image](https://github.com/user-attachments/assets/bf5cb412-7d58-4d92-a4d6-0452b1033d46)

**Comment by Kagekazu** [comment]
id have to doublecheck in game, but i remember there is an option to offset it.

**Comment by KSVKovrov** [comment]
Modifying the offset to 0.5 seems to fix the issue and makes it match the exact weaponskill range, thanks for the pointer.

**Comment by Tartarga** [comment]
Just for some clarification, housing dummy hitboxes are weird. They don't place nice.  I always recommend trying against dummies in fields or in Exploration Dungeon mode for more of a real world result

**Comment by zbee** [comment]
By the way, this led to #151. Your setting of 0.5 will no longer be needed.
