### ISSUE TITLE
GNB Gnashing Fang Continuation Appears on Keen Edge Instead

### ISSUE THREAD

**Issue by Add1ctedM** [PunishXIV/WrathCombo#144]
I saw there was an issue about this or something similar made a few days ago, but it seems like the fix might not have entirely worked. I have continuation option enabled for Gnashing Fang features, but using Gnashing Fang puts the continuation buttons on Keen Edge instead. The only other options I have enabled for GNB are hypervelocity for Burst Strike (which does work correctly) and AOE advanced mode with none of the extra options enabled.

Also perhaps a secondary issue, not sure if intended, but having said option enabled also replaces Keen Edge with the Gnashing Fang combo after the first step of the combo. Again not sure if that's intended or not since I know that doing your normal combo does drop gnashing fang but just wanted to be sure it was known in case that wasn't intended. 

![Screenshot (23)](https://github.com/user-attachments/assets/c4787ce8-a9fd-46d8-82c4-b8f2a97e1fc6)
![Screenshot (24)](https://github.com/user-attachments/assets/8fd5db07-0209-4a3a-a64e-a7c2f7691183)

**Comment by zbee** [comment]
The fix for #103 has not been released yet.
It will be fixed sometime (probably shortly) after #115 is merged.
