### ISSUE TITLE
[MNK] HP% limit to stop using RoF set incorrectly.

### ISSUE THREAD

**Issue by ahernika** [PunishXIV/WrathCombo#156]
Looks like check is made on RoF in the code, but the options display as check on RoW. If its actually check on RoW, then can we please add check of RoF as well.
![image](https://github.com/user-attachments/assets/2af2cac2-fc57-4150-8aab-fb69db3c64b9)
![image](https://github.com/user-attachments/assets/95d53757-9e48-4cdb-b7a9-b370934f9eee)

https://github.com/PunishXIV/WrathCombo/blob/534e4fc95f8551960d88fe282f21406c89ff1f9b/WrathCombo/Combos/PvE/MNK/MNK_Config.cs#L62-L63
thanks zbee for pointing me to the line in the code.

**Comment by Kagekazu** [comment]
Ah, was too quick to add it, I'll make a PR to solve it.
