### ISSUE TITLE
[Core] the new "/wrath combo off" comand messes with the rotations

### ISSUE THREAD

**Issue by timetowipe** [PunishXIV/WrathCombo#166]
Issue reopened per conditions set by Zbee [here](https://discord.com/channels/1001823907193552978/1271175781569003590/1312855159252058193)

Using /wrath combo off makes the openers not to be followed at all, examples can be seen in closed issue #152. As requested by Kage [here](https://discord.com/channels/1001823907193552978/1271175781569003590/1312828921745637378) i swapped to RDM and the issue was reproduced. This causes the entire fight length rotation to be completely off. 

This is in full auto mode. Using the comand /wrath combo on remedies all the issues and the rotations return to normal. I tried with no ping fix plugin (alex, no clippy, VBM), and with all of them, including changing VBM to 50. The issue persisted regardless if i used the comand /wrath combo off.

**Comment by timetowipe** [comment]
Video evidence of the problem. https://drive.proton.me/urls/TAETMXWAQC#vItFlj7Hclqq

**Comment by Kagekazu** [comment]
I watched the video, do u use Reassemble - Air anchor manually?
Casue if u press split shot, it starts the Wrath rotation, and so uses the opener

**Comment by Kagekazu** [comment]
> I do as air anchor pre pull is how you do the opener, not split shot. I do the same pre pull stuff on wrath combo on as I do wrath combo off, reassemble>air anchor. It's even what wrath combo does of you do it in full manual mode.

Can u try to just press split shot and let it do its thing? it should do split shot - prepull - opener
(cant use prepull with combo off)

**Comment by zbee** [comment]
The incorrect starting of the opener is mostly addressed with our new opener system in #206.
