### ISSUE TITLE
[MCH] Double Dismantle Protection doesn't work

### ISSUE THREAD

**Issue by neongrey** [PunishXIV/WrathCombo#170]
I'm not sure that this is new either, because it's not often that I'm both paying attention to my mits and there is another machinist in the party who also cares about mitting, but it happened today. I've got it enabled and it never once protected it. Something seems wonky with the physical ranged DPS double mitigation feature too-- when it was supposed to be locking out Tactician, it would re-enable while my GCD was rolling. I'm not sure if that's related or if that's separate. I don't have the Dismantle - Tactician enabled, also.

**Comment by Kagekazu** [comment]
> when it was supposed to be locking out Tactician, it would re-enable while my GCD was rolling.

Can u check if it works for any other phys ranged class? i.e with troubadour or shield samba?

> I've got it enabled and it never once protected it.

Can u check if it works for Feint or Addle?

**Comment by Kagekazu** [comment]
Found the issue for Dismantle, they changed the ID of the debuff. So will fix it next update ^.^

The tactician protection should still work tho.
