### ISSUE TITLE
[Core] Syncing under 60 (?) seems to not adapt for level difference and lock abilities out

### ISSUE THREAD

**Issue by PikachusDimples** [PunishXIV/WrathCombo#172]
Had this on Dragoon and Bard now. Normally when under sync rules the app will "skip" any abilities that cannot be used for the level, no matter your actual job settings.

However, having my mostly played jobs at 100 when going into a sync situation (I've noticed it under 60) the app tries to use skills that are too high, locking the box up.

I was wondering if you have changed this going from Sloth to Wrath, and will require us to re-do our chosen abilities under sync conditions, or is this is an unintended occurrence. 

Thanks for your time and your effort in your projects.

**Comment by Kagekazu** [comment]
I will doublecheck Dragoon tomorrow, but I've just done lvl 50 content on Sam, Mch, mnk and rpr without issues

**Comment by PikachusDimples** [comment]
If I catch it I'll try and get a video for you, sure.

It just pops the ability in there (example Windbite) when in a dungeon under 30, for example.

**Comment by PikachusDimples** [comment]
Here is a IMGBB link to a screenshot I made that illustrates the issue.

I'd rather not share a video if you don't mind.

https://ibb.co/rQdJPgH

Had similar with DRG in a level 60 Normal Raid. too.

**Comment by edewen** [comment]
https://github.com/PunishXIV/WrathCombo/pull/161 The bard issue was specifically my fault not a wrath thing. i implemented a new dot management system and forgot a lvl check. fixed in pr

**Comment by Kagekazu** [comment]
> Had similar with DRG in a level 60 Normal Raid. too.

Which skill? I tought I lvlchecked them all, but I'll doublecheck tomorrow!

**Comment by Kagekazu** [comment]
Any update on this?

I cant seem to break any of my classes below 60.

**Comment by PikachusDimples** [comment]
Sorry for late reply, been unwell.

I believe it was updated today? Looks fine right now, so whatever needed fixing looks like it got sorted.

Thank you for your exhaustive effort in this.
