### ISSUE TITLE
[MCH] AoE opener at 100 wastes a Reassemble when flamethrower is enabled

### ISSUE THREAD

**Issue by neongrey** [PunishXIV/WrathCombo#173]
With the trash pulls in Jeuno being some actual great places to use flamethrower, I re-enabled it in my AoE combo. Unfortunately, what happens is you have the opening Bioblaster, then a Reassemble, then going right into Flamethrower; since Flamethrower lasts longer than Reassemble's duration, this always wastes the Reassemble. Also, if you abort the Flamethrower early, the combo just chokes and stays on the now on-cooldown Flamethrower until such time as its duration would have expired naturally.

Got a log from the fight, if that helps: https://www.fflogs.com/reports/Kr7RTpcN6qDx9AML#fight=15&type=damage-done&source=3

**Comment by Kagekazu** [comment]
AoE doesnt have an opener.
But i can make it so it doesnt reassemble.

Ty for letting me know, i hardly use AoE :D
