### ISSUE TITLE
[MNK] Even burst windows (in Advanced Mode) deviate from The Balance

### ISSUE THREAD

**Issue by Whitemoose78** [PunishXIV/WrathCombo#174]
Normally a beast-chakra handler user for extra control, but I'm liking the instant forbidden chakra usage of the adv rotation with manual RoF/Brotherhood activation.
The rotation does the job well, it does the double lunar opener properly, and builds a solar nadi on the odd minute. First blitz of the even minute burst it only uses opo GCDs, but the second blitz it always builds a solar nadi, whereas more opo's (and thus a lunar) in the even burst is more potency. I take it this prioritization is a relic from 6.x monk slothcombo, as there you would want a solar under 2min buffs to buff the Demolish DoT.
For reference, it fails to do the triple opo in the latter part:
![](https://i.imgur.com/V3mnf9Q.png)

**Comment by Kagekazu** [comment]
I already talked about it in a discord issue.
![image](https://github.com/user-attachments/assets/4a9cc990-214e-4922-bc08-eaac1576674b)

But my PR fixes that it will always do Lunar after Phantom Rush
