### ISSUE TITLE
 [MCH] For some reason Savage Blade become a part of AOE combo?

### ISSUE THREAD

**Issue by Comnislasher** [PunishXIV/WrathCombo#175]
![Screenshot 2024-12-04 225313](https://github.com/user-attachments/assets/1f20e7c2-0cab-4475-b321-95e83677147e)
For some reason plugin after Flamethrower tried to execute Savage Blade? Which isn't even an active skill in the game. In my case this is a stable bug which appear after Flamethrower usage.

**Comment by Kagekazu** [comment]
It's not a bug. 
It's there so u don't interrupt flamethrower since it's a channelled ability. 

It doesn't say it in simple mode, but in advanced it's in the tooltip.
