### ISSUE TITLE
[BLM] Transpose not being used

### ISSUE THREAD

**Issue by pinkencat** [PunishXIV/WrathCombo#177]
When running Wrath as thaumature/blm the plugin never uses transpose, either in simple or advanced mode with transpose option set. 

In auto rotation mode this means that when the MP bar is empty after fire casts, the rotation just stops. It doesn't attempt to transpose or even start casting blizzard.

When casting blizzard and the MP bar reaches full, rotation does not use transpose and instead just starts casting fire instead.

**Comment by Kagekazu** [comment]
Will be fixed next update.
