### ISSUE TITLE
[MNK] Adv. Rota still using solar after even minute phantom rush

### ISSUE THREAD

**Issue by Whitemoose78** [PunishXIV/WrathCombo#189]
Supposedly this issue (same as #174, solar nadi being built after phantom rush in buffs) was fixed, but the behaviour is still the same. Tried it with adv rota with everything ticked, as well as my personal setup (manual PB/buffs), still a solar nadi is being built in both cases.
![image](https://github.com/user-attachments/assets/c78f17d9-5683-442c-bd2c-523f6c42e084)
I'm sorry in advance Kage xD

**Comment by Kagekazu** [comment]
Got a log where it happens? 
I'll doublecheck on my end aswell

**Comment by Kagekazu** [comment]
![image](https://github.com/user-attachments/assets/07bf98bf-b29c-4c27-8664-02dea8c6ed77)

On my testing build it works, so probably once the new opener system is in, it works how it should!
