### ISSUE TITLE
[SGE]Auto Rotation Infinite Eukrasian Spam

### ISSUE THREAD

**Issue by TrexelCat** [PunishXIV/WrathCombo#199]
If damage is done to reach the threshold to require auto rotation to attempt to heal. Auto rotation will get locked into an infinite Eukrasian spam loop until all party members HP regenerate to an appropriate level to no longer cause auto rotation to want to heal them.

If the AOE heal requirements are met, Auto rotation will spam Eukrasian Prognosis, regardless of if the setting is ticked for shield check.
If only a single party member is injured, auto rotation will spam Eukrasian Dosis on the enemy.

Auto rotation will only return to normal damage rotation once all party members health are above the threshold for healing, either via normal regeneration or from Eukrasian Prognosis spam.

Suspected cause:
Switching targets too fast. For single target heals, it selects the target that requires the healing, then switches back to enemy target as soon as the animation for Eukrasia starts, before actual healing can take place. Causing the prepared Eukrasia to fire off Eukrasian Dosis on the enemy, instead of Eukrasian Diagnosis on the party member that needs healing.

Unknown cause as to why for AOE healing it will continually spam Eukrasian Prognosis and ignore the shield check other than it is also trying to do single target healing as well, which would cause it to use Eukrasia just before it tries to use normal Prognosis.

Tested in The Porta Decumana with Duty Support.

Attempts to remedy the situation before submitting an issue:
Disabling Eukrasia use. - Results in only Diagnosis/Prognosis being used. Sometimes only going off on player instead of intended target as that is the default game behavior if a non-healable target is selected when a heal is used.
Restarting the Duty. - Same behavior as listed in issue.
Restarting the game. - Same behavior as listed in issue.
Restarting computer. - Same behavior as listed in issue.
Changing game framerate. - Same behavior as listed in issue.
(I have FFXIV force limited in my graphics drivers to 60fps as that is the limitation of my monitor. I tried unlimited, 58, and 30.)

Potential conflicts(?):
I use [AutoDuty](https://github.com/ffxivcode/AutoDuty) to level alt jobs and to farm for Alagan Tomestones. And there is a not 0% chance that there might be a conflict between the two mods. However, WrathCombo is listed as one of the supported addons for auto combat rotation, so I mostly doubt this. But, as the two of them are supposed to work together, I still felt it was worth mentioning.

**Comment by zbee** [comment]
Please add the output of running `/wrath debug sge` in game to your post.

**Comment by TrexelCat** [comment]
> Please add the output of running `/wrath debug sge` in game to your post.

START DEBUG LOG

Plugin Version: 1.0.0.5
Installation Repo: https://love.puni.sh/ment.json

Conflicting Plugins: 0
Current Job: sage / Sage / SGE
Current Job Index: 40
Current Job Level: 100

Current Zone: The Roost
Current Party Size: 1

START ENABLED FEATURES
14001 - SGE_ST_DPS
14002 - SGE_ST_DPS_Lucid
14003 - SGE_ST_DPS_EDosis
14004 - SGE_ST_DPS_Movement
14005 - SGE_ST_DPS_Phlegma
14006 - SGE_ST_DPS_Kardia
14007 - SGE_ST_DPS_Rhizo
14008 - SGE_ST_DPS_Psyche
14009 - SGE_AoE_DPS
14010 - SGE_AoE_DPS_Phlegma
14011 - SGE_AoE_DPS_Toxikon
14012 - SGE_AoE_DPS_Lucid
14013 - SGE_AoE_DPS_Rhizo
14014 - SGE_ST_Heal
14015 - SGE_ST_Heal_Esuna
14016 - SGE_ST_Heal_Kardia
14017 - SGE_ST_Heal_EDiagnosis
14018 - SGE_ST_Heal_Soteria
14019 - SGE_ST_Heal_Zoe
14020 - SGE_ST_Heal_Pepsis
14021 - SGE_ST_Heal_Taurochole
14022 - SGE_ST_Heal_Haima
14023 - SGE_ST_Heal_Rhizomata
14024 - SGE_ST_Heal_Krasis
14025 - SGE_ST_Heal_Druochole
14026 - SGE_AoE_Heal
14027 - SGE_AoE_Heal_Physis
14028 - SGE_AoE_Heal_EPrognosis
14030 - SGE_AoE_Heal_Holos
14031 - SGE_AoE_Heal_Panhaima
14032 - SGE_AoE_Heal_Pepsis
14033 - SGE_AoE_Heal_Ixochole
14035 - SGE_AoE_Heal_Kerachole
14036 - SGE_AoE_Heal_Rhizomata
14043 - SGE_OverProtect
14044 - SGE_OverProtect_Kerachole
14045 - SGE_OverProtect_SacredSoil
14046 - SGE_OverProtect_Panhaima
14047 - SGE_OverProtect_Philosophia
14050 - SGE_AoE_Heal_Philosophia
14051 - SGE_AoE_DPS_Psyche
14052 - SGE_AoE_DPS_EDyskrasia
14053 - SGE_AoE_DPS_AddersgallProtect
14054 - SGE_ST_DPS_AddersgallProtect
14055 - SGE_ST_DPS_Opener
14056 - SGE_ST_DPS_Soteria
14057 - SGE_AoE_DPS_Soteria
END ENABLED FEATURES

START CONFIG SETTINGS
SGE_ST_DPS_Adv - False
SGE_ST_DPS_EDosis_Adv - NOT SET
SGE_ST_DPS_Movement - True, False, False, True
SGE_ST_DPS_EDosisHPPer - 1
SGE_ST_DPS_Lucid - 5000
SGE_ST_DPS_Rhizo - 0
SGE_ST_DPS_AddersgallProtect - 3
SGE_AoE_DPS_Lucid - NOT SET
SGE_AoE_DPS_Rhizo - 0
SGE_AoE_DPS_AddersgallProtect - 3
SGE_ST_DPS_EDosisThreshold - NOT SET
SGE_ST_Heal_Adv - False
SGE_ST_Heal_UIMouseOver - False
SGE_ST_Heal_IncludeShields - False
SGE_AoE_Heal_KeracholeTrait - False
SGE_ST_Heal_Zoe - 50
SGE_ST_Heal_Haima - 50
SGE_ST_Heal_Krasis - 50
SGE_ST_Heal_Pepsis - 50
SGE_ST_Heal_Soteria - 50
SGE_ST_Heal_EDiagnosisHP - 100
SGE_ST_Heal_Druochole - 50
SGE_ST_Heal_Taurochole - 50
SGE_ST_Heal_Esuna - 75
SGE_ST_Heals_Priority - NOT SET
SGE_AoE_Heals_Priority - NOT SET
SGE_ST_Heal_EDiagnosisOpts - False, True
SGE_Eukrasia_Mode - 0
EmergencyHealThreshold - NOT SET
EmergencyGuardThreshold - NOT SET
QuickPurifyStatuses - NOT SET
END CONFIG SETTINGS

Redundant IDs found: 0
Status Effect Count: 0
START STATUS EFFECTS
END STATUS EFFECTS
END DEBUG LOG

**Comment by Taurenkey** [comment]
When it comes to autorotation, the physical target selection is more or less an illusion. Actions can be cast onto targets without any sort of targeting (that's how ReAction works). Our autorotation just puts your target onto whatever is being attacked/healed for user clarity. As such, I don't think that's the cause.

I had personally noticed a similar behaviour on WHM which made me readdress the autorotation controller code to streamline priority for healing versus DPS. In the next version, it should be a bit smarter in making sure you heal before going back to DPSing. As such, once 1.0.0.6 is out, if you still experience this issue please comment.
