### ISSUE TITLE
[AutoRot]Auto Rotation does not engage at the extreme edge of melee combat

### ISSUE THREAD

**Issue by TrexelCat** [PunishXIV/WrathCombo#200]
I use [AutoDuty](https://github.com/ffxivcode/AutoDuty) to level alt jobs and to farm for Alagan Tomestones. When running it with a melee job, auto rotation does not activate if at the extreme edge of melee range.

Manual activation of the desired rotation however, does work, even at the extreme edge of melee range.

Tested with Monk and Reaper, in various Duty Support.

AutoDuty will set the combat range for the player character based on the job that is currently active when the mod is triggered to start a loop. When a viable enemy target is selected and combat has started, the AutoDuty AI will move the player character into the desired combat range(casting range for ranged, melee range for melee) so that that the player character can participate in the combat.

However, at the extreme range of melee, combat does not start, and/or does not use skills auto rotation.

If "dragged" into position as soon as combat starts, auto rotation does not trigger and thus auto attack does not start.
If "dragged" to a new position because enemy moved and combat has already started, auto attack will continue, but no auto rotation unless the enemy moves one or two pixels closer to the player character.
(I don't know the exact movement required for the enemy to move closer, just looks like one or two pixels)

Changing the melee distance in the settings does not fix this.
Setting it to a negative number just causes the auto rotation to assume player character is out of range, even if they aren't, and if configured for it starts using ranged filler(Monk does not have a ranged filler).
Changing it to a positive number does nothing.

The really odd part is, even if configured for ranged filler, at this magical point at the extreme edge of melee range, it will do nothing. No ranged filler, no melee auto rotation.

I know the player character is in range as, if the auto attack has triggered at any point in the fight, the player character will still auto attack as normal. And if I am physically sitting there and watching for when this happens, and I manually trigger the one button combo, that will activate correctly and fire off what it's configured for.

I have also tested this with AutoDuty disabled. And, while it's hard for a player to replicate the circumstances to the pixel, it can be done. And has shown that AutoDuty is not the cause of this(Only that it can replicate it more consistently).

**Comment by Kagekazu** [comment]
This is fixed in PR #190 iirc, but correct me if im wrong
