### ISSUE TITLE
[MCH] Simple mode - Single target getting stuck on "hotshot"

### ISSUE THREAD

**Issue by wolfsinger01** [PunishXIV/WrathCombo#211]
Hello!

Since the latest version 1.0.0.5, the MCH simple single target rotation keeps getting stuck on the skill HOT SHOT showing darkened.   Eventually it will continue on once some other skill's cool down is over.

**Comment by Kagekazu** [comment]
Fix is already merged. Will be solved next update.

Easy workaround is use advanced with everything enabled.
