### ISSUE TITLE
[NIN] Minor ninja issues

### ISSUE THREAD

**Issue by nativepapaya** [PunishXIV/WrathCombo#212]
EDIT: See 3rd post for ninki issue/fix.

There are some weaving issues with ninja which might cause some GCD to be missed during kunai window. There is also some ninki being wasted when using ~~Metsui~~ Dokumori. For ~~Metsui~~ Dokumori, maybe use a bava to dump any ninki if around 50 in order to avoid overcapping before using Metsui.

Provided the log below testing on a training dummy.

**xivanalysis**
https://xivanalysis.com/fflogs/a:CY8a9vWQ3pRPfG47/6/3

**Debug**
[WrathDebug.txt](https://github.com/user-attachments/files/18200347/WrathDebug.txt)

**Comment by nativepapaya** [comment]
After looking at the code, it seems the issue with the ninki might be related to this part.

`                        if (IsEnabled(CustomComboPreset.NIN_ST_AdvancedMode_Bhavacakra) &&
                            ((NINHelper.TrickDebuff && gauge.Ninki >= 50) || (useBhakaBeforeTrickWindow && gauge.Ninki >= 85)) &&
                            (IsNotEnabled(CustomComboPreset.NIN_ST_AdvancedMode_Mug) || (IsEnabled(CustomComboPreset.NIN_ST_AdvancedMode_Mug) && IsOnCooldown(Mug))) &&
                            Bhavacakra.LevelChecked())
                            return OriginalHook(Bhavacakra);`

It will try to hold ninki for trick attack, which makes sense, but it seems it will hold it even if capped, causing you to waste some of the ninki generated by your 123 combo, which can add to a lot over the course of a fight.

**Comment by nativepapaya** [comment]
I believe I found what the Ninki issue is. Turns out there isn't a check for the amount of Ninki the player has before using Mug/Dokumori. For mug there is no issue but Dokumori gives you 40 Ninki on used, causing you to overcap.

**Comment by zbee** [comment]
At least to me those changes make good sense, particularly the ninki reduction, especially so with pending `CanDelayedWeave` updates to make it a bit smoother/more reliable.
Ping me on Discord when you have that made, and I'll review both your PRs to try to get them moving again.

**Comment by zbee** [comment]
#219 closed this.
