### ISSUE TITLE
[GNB] Gnashing Fang into Continuation does not appear to function

### ISSUE THREAD

**Issue by theconnstruct** [PunishXIV/WrathCombo#237]
As of 1.0.0.7, Gnashing Fang -> Continuation does not appear to be functional. I believe this was intended to be fixed by #195.

I am seeing the same issue as the previous. I expect Gnashing Fang to switch to the appropriate Continuation, but this does not seem to happen.

[WrathDebug.txt](https://github.com/user-attachments/files/18241254/WrathDebug.txt)

Edit to add: Every other continuation option (Burst Strike > Hypervelocity, Fated Circle > Fated Brand) works correctly. It's just GF that doesn't.

**Comment by Kagekazu** [comment]
@Akechi-kun any idea?
