### ISSUE TITLE
Cloud Of Darkness Chaotic "All Content/Boss Only" content

### ISSUE THREAD

**Issue by MaddoxMaxx** [PunishXIV/WrathCombo#241]
Cloud of Darkness boss does not seem to register as being "Boss-Only" content for that option for Balance Opener checks. When its on boss only mode itll swap to a normal spell than the normal programmed opening cast. EX: PCT would normally pull with Rainbow Drip but with boss only enabled it defaults to Fire In Red.

**Comment by zbee** [comment]
> dev note: the `CFC` and `ContentType` from `EC.GameHelpers.Content` would need checked for what the Chaotic is for it to be added.

**Comment by Kagekazu** [comment]
Tauren added it for next release
