### ISSUE TITLE
Astro "play weave option" occuring though unchecked 

### ISSUE THREAD

**Issue by Astrouser03** [PunishXIV/WrathCombo#242]
I have play weave option turned off because I like placing the cards on dps myself but for some reason though its unchecked during my opener is replaced malefic with the balance or spear depending on what cards are drawn and will play them. Not a big issue but it seems to be inconsistent, so when I adapt It reverts to me having to it manually and then when I adapt to do it myself it replaces malefic and does it atomically.

**Comment by zbee** [comment]
Openers are hard-coded to match The Balance as exactly as possible, and as such: do not receive any influence from other options at all.

When you do it manually, or a variety of other things, it fails the opener, and as such starts following your option choices again; I think you'll find that if you go to Misc Settings and tick the last box, you'll be able to see this happening more clearly.

This is intended behavior.
