### ISSUE TITLE
[BLM] single target combo gets stuck in opener

### ISSUE THREAD

**Issue by qnesp1987** [PunishXIV/WrathCombo#254]
right around the time iin the opener where it should use manafont it freezes. cant press anything

**Comment by zbee** [comment]
@Taurenkey am I correct in assuming that the opener and caster-specific opener changes coming in 1.0.0.8 would address this issue?

**Comment by Kagekazu** [comment]
can u also post the file from /Wrath debug BLM?

**Comment by zbee** [comment]
I believe this will be fixed by 5f66460 and ce73955, which will come in 1.0.0.8.
Please comment/reopen if not.

**Comment by PhoenixtheII** [comment]
I still get stuck having the balance 100 enabled
