### ISSUE TITLE
[SMN] Option to replace Emerald Ruin III with Ruin III

### ISSUE THREAD

**Issue by GayPotatoEmma** [PunishXIV/WrathCombo#41]
Since in some content (most notably Eureka/BA) your GCD is quite a bit lower (2.12s in my case), using Emerald Ruin III ends up being a damage loss over just using Ruin III it would be nice to have an option to just not use ER3.

After level 72 this would not be relevant as it is then replaced by the higher potency Emerald Rite.

[originally submitted as [XIVSlothCombo #1857](https://github.com/Nik-Potokar/XIVSlothCombo/issues/1857)]

**Comment by Genesis-Nova** [comment]
I'm not really too fussed about adding sub-max level optimizations for niche content.
You're more than welcome to just use Ruin III manually as that is excluded from ability replacements.
