### ISSUE TITLE
[SMN] Egi summons hafe only aoe option

### ISSUE THREAD

**Issue by Dimaff14** [PunishXIV/WrathCombo#43]
[SMN] Egi summons hafe only aoe option if aoe und solo target advanced feature activated.

**Comment by edewen** [comment]
Running aoe and st advanced and both are fine using the correct abilities. rites vs catastrophes. is this level specific? any details?

**Comment by Genesis-Nova** [comment]
I'll take a look at this, recently reinstalled windows so I don't have everything up and running.

**Comment by zbee** [comment]
@Dimaff14 Can you confirm this is still an issue? If so, can you provide any of the details requested by edewen and genesis?

**Comment by zbee** [comment]
Stale. Perhaps fixed as of 1.0.0.5 anyway.
