### ISSUE TITLE
[VPR] Advanced Mode Single Target broke

### ISSUE THREAD

**Issue by Omnicrone** [PunishXIV/WrathCombo#79]
As of last update, Advanced Mode Single Target for Viper broke. The main combo path, Vicewinder combo option and Reawaken combo option all do not work anymore.

**Comment by Kagekazu** [comment]
Fixed in PR #62

**Comment by PikachusDimples** [comment]
Not sure if connected, but Pug/Monk too appears broken (Advanced Single target and Basic Single Target).

**Comment by Kagekazu** [comment]
SAM/BLM/MCH/MNK/DRG 

will all be fixed with the linked PR

**Comment by PikachusDimples** [comment]
> VPR/SAM/BLM/MCH/MNK/DRG/RPR
> 
> will all be fixed with the linked PR

Thank you for your work!
