### ISSUE TITLE
[Feature Request] API 10 Support

### ISSUE THREAD

**Issue by Arckzzzzz** [PunishXIV/WrathCombo#82]
For CN players, we may have to wait for three or four months to receive the release of patch 7.1 to use the API 11.
Before that, we will not be able to use WrathCombo since it only has API 11 support.

Is there any chance to release an API 10 branch?

**Comment by zbee** [comment]
This would be easier in retrospect than it is now, and it also would have been easier if Lumina did not receive a massive upgrade that changed a fair chunk of what we do in Wrath Combo.

As it is now, I do not think this will happen.
Will assign Tauren and Kage as they both did updates to Wrath, maybe one would be willing to reverse that work.

**Comment by Taurenkey** [comment]
It's not feasible. We don't have access to the CN version of the game so it will have to be the responsibility of someone in the CN community to maintain a fork for that region.
