### ISSUE TITLE
[Feature Request] Prioritization of Manual Input

### ISSUE THREAD

**Issue by Flammablegelatin** [PunishXIV/WrathCombo#83]
Is it possible to make it so that manual input will override the auto rotation feature? There are cases where one is unable to queue a manual action due to the auto rotation, and no way to force it other than to turn off auto rotation temporarily.

**Comment by zbee** [comment]
Would also like to see this, not sure how to implement it though; would almost certainly be up to Tauren.

**Comment by darkedone02** [comment]
I posted this also on the discord.

https://discord.com/channels/1001823907193552978/1308961882618728568/1308961882618728568


"When experimenting with the usage of the auto-rotation feature, i've noticed that the usage of flamethrower, the auto-rotation will not let it use it's full duration of it, skipping damage (considering flamethrower got buffed this patch).

Another issues with auto-rotation is the issue of overriding so much that it's hard to actually get mit though, IE tactician and dismantle.

If possible, put a delay on the auto-rotation for the full usage of flamethrower if used, Also put a priority system in place where our inputs matter more then the the auto-rotation so mitigations can go through."

**Comment by Taurenkey** [comment]
I've made some changes to the operation of the Auto-Rotation such that it won't queue anything, meaning manually inserting an action should be easier.
