### ISSUE TITLE
[feature request] bard ogcd options

### ISSUE THREAD

**Issue by hhharkness** [PunishXIV/WrathCombo#86]
currently the single target ogcd feature adds songs rotation, and the aoe one doesn't include pitch perfect. an option for both that just adds empyreal arrow+sidewinder+pitch perfect would be great!

**Comment by edewen** [comment]
So you want a single ogcd that doesn't add songs?

**Comment by hhharkness** [comment]
yes! but that still includes pitch perfect - and adding pitch perfect for the aoe one

**Comment by edewen** [comment]
pitch perfect is in the aoe one

**Comment by hhharkness** [comment]
well if it is then it isn't working for me 😅 this is with both features enabled

https://github.com/user-attachments/assets/557297ca-b589-42b5-adb5-52a144cbb667

**Comment by edewen** [comment]
Im going to assume you dont have action change set on wanderers to turn to PP. the code was weird. using pp hook for st but wanderers hook for aoe.

Ill just switch wanderers hook to PP hook and its all better.
