### ISSUE TITLE
[bug] machinist reassemble priority

### ISSUE THREAD

**Issue by hhharkness** [PunishXIV/WrathCombo#87]
on the single target advanced mode reassemble option, if all uses are checked but air anchor is not unlocked it still prioritises hot shot above drill. obviously i could just uncheck use on air anchor but i'm assuming this would still be an issue in synced content below 76

**Comment by Kagekazu** [comment]
Can u check once PR #62 is merged?

If it still happens then, then ye its a bug, since normally it should prio Drill and before drill it should use cleanshot.
Ill investigate already either way.

Ty!

**Comment by Kagekazu** [comment]
also wondering, does it happen in Simple mode aswell?

**Comment by hhharkness** [comment]
yep acts the same way!

**Comment by github-1348A55** [comment]
I know this isn't the right place to post, but I'll report it as an issue for the same job.

When I enable Simple Mode - AoE and run Flamethrower manually
 Savage Blade a PLD skill that was removed in 5.0, appears in the AoE rotation.

**Comment by zbee** [comment]
> Savage Blade a PLD skill that was removed in 5.0, appears in the AoE rotation.

That is intentional behavior to help prevent you from cancelling the ability; please ask in the discord or create for a further information so as to help keep this issue on topic though.

**Comment by github-1348A55** [comment]
> > Savage Blade a PLD skill that was removed in 5.0, appears in the AoE rotation.
> 
> That is intentional behavior to help prevent you from cancelling the ability; please ask in the discord or create for a further information so as to help keep this issue on topic though.

Ah, I didn't realize this was meaningful behavior.
I think it would be better to add a dummy warning to the feature description.
Maybe someone else will report the same mistake in the future.

**Comment by Kagekazu** [comment]
It has that dummy warning on Advanced - Flamethrower
![image](https://github.com/user-attachments/assets/a4a8d6c5-5920-4ac1-afaa-d317b025291c)

Its a bit weird to add it on the simple mode description.

**Comment by Kagekazu** [comment]
> yep acts the same way!

alright, ill do some internal testing then, thanks already!

**Comment by hhharkness** [comment]
tested with the new update and it's still behaving the same way for me unfortunately, on both simple and advanced mode

**Comment by Kagekazu** [comment]
ill have a look tomorrow then. it should only use reassemble when its air anchor, since i dont check reasseble for hot shot

**Comment by Kagekazu** [comment]
> tested with the new update and it's still behaving the same way for me unfortunately, on both simple and advanced mode

Can u send me an fflog of where it happens? cause i cant find anything in the code for this

**Comment by zbee** [comment]
@hhharkness Please re-check on 1.0.0.4, and provide a log or at least a brief video clip.

**Comment by hhharkness** [comment]
sorry for late response, haven't had time to play in a few days. did some testing on a dummy and figured out that it's seemingly only happening in the opener - when out of combat and everything is off cooldown reassemble is shown followed by hot shot if used, but if i initiate combat by right clicking it changes to hot shot and puts reassemble on drill. happy to still provide logs if needed just not quite sure how to 😅


https://github.com/user-attachments/assets/25653127-1d43-4360-a90d-6f0d4d7d86f7

**Comment by Kagekazu** [comment]
> sorry for late response, haven't had time to play in a few days. did some testing on a dummy and figured out that it's seemingly only happening in the opener - when out of combat and everything is off cooldown reassemble is shown followed by hot shot if used, but if i initiate combat by right clicking it changes to hot shot and puts reassemble on drill. happy to still provide logs if needed just not quite sure how to 😅
> 
>  241201.070152.mp4

Ye, i cant fix that issue, since its set to show reassemble before u enter combat, and it goes down the list of tools from top to bottom

so it will always do 
- Excavator
- Drill
- Air anchor/Hotshot
- Drill

I have tried to change that to not include hotshot, but then it breaks on lower lvls. So im keeping it as is for now.
