### ISSUE TITLE
[feature request] reaper gluttony option

### ISSUE THREAD

**Issue by hhharkness** [PunishXIV/WrathCombo#88]
would love an option somewhere between what #43 and #44 do, adding enshroud, lemure's slice/scythe and sacrificium (ogcd) but not void/cross reaping, communio or perfectio (gcd)

**Comment by Kagekazu** [comment]
![image](https://github.com/user-attachments/assets/f02dbe7c-ab23-4e3c-88a4-35fae29fd1b4)
