### ISSUE TITLE
Auto ON/OFF on server bar.

### ISSUE THREAD

**Issue by Xehanort09** [PunishXIV/WrathCombo#91]
Have an option to completely get rid of it. I don't use auto at all and there is no simple check box to get rid of it like other plugins.

**Comment by Kagekazu** [comment]
> Have an option to completely get rid of it. I don't use auto at all and there is no simple check box to get rid of it like other plugins.

As we got pinned in Discord;
![image](https://github.com/user-attachments/assets/2aae4069-b89c-4a4c-ad69-060eb18983f5)
