### ISSUE TITLE
[Bug] RDM Enchanted Riposte combo breaks

### ISSUE THREAD

**Issue by t-l13** [PunishXIV/WrathCombo#94]
Something causes Red Mage's Enchanted Riposte combo to break when using this mod. These are the settings I'm using: 

- Single Target DPS Feature (aka advanced option)
- Single Target Melee Combo Option
- Advanced Action Option: Riposte instead of Jolt.

I don't understand the function of this, but it seems that the mod will correctly go from Enchanted Riposte -> Enchanted Zwerchau, then revert to Enchanted Riposte instead progressing to Enchanted Redoublement. This has been somewhat random and I'm not sure what reproduces it. I tried it with and without ability weaving and got mixed results for each.

[Here is a clip showing the problem.](https://gyazo.com/3b85f91e738bfa62c10123cf65fa8795)

This is also probably related to the broader issue I posted about [here](https://github.com/PunishXIV/WrathCombo/issues/93) with combo paging, but I made a separate ticket for RDM because it is not just a display bug and actually causes their Riposte combo to fail.

**Comment by zbee** [comment]
Can you please provide an fflog or xivanalysis link? You can provide this anonymously by clicking [this](https://files.catbox.moe/q3ofpk.gif), and sharing that link.

**Comment by t-l13** [comment]
https://xivanalysis.com/fflogs/zdxF7L6JnwyvrmAM/5/2 This has the parse with the problem. It's at the 5 minute mark.

**Comment by zbee** [comment]
At the 5 minute mark the reason the combo broke is because of the dummy's level causing you to miss:
![image](https://github.com/user-attachments/assets/db81fa8b-d79e-406d-8bc8-83e71e7574ea)

Which you can see in your clip:
![image](https://github.com/user-attachments/assets/1617dca2-14de-4bb1-946b-0e04a837b43c)

Can you replicate this behavior on a level 1 dummy?

**Comment by zbee** [comment]
Seems as though that was the source of the issue. Closing.
